version: '3.8'

services:
  caddy:
    build: caddy/.
    restart: unless-stopped
    ports:
    - 80:80
    - 443:443
    volumes:
    - ./caddy/Caddyfile:/etc/caddy/Caddyfile
    env_file:
    - caddy/caddy.env

  unifi-controller:
    image: linuxserver/unifi-controller
    restart: unless-stopped
    environment:
    - PUID=1000
    - PGID=1000
    - MEM_LIMIT=1024M
    ports:
    - 3478:3478/udp
    - 10001:10001/udp
    - 8080:8080
    - 8443:8443
    - 1900:1900/udp
    - 8880:8880
    - 6789:6789
    - 5514:5514
    volumes:
    - ~/unifi-controller:/config

  bitwarden:
    image: bitwardenrs/server
    restart: unless-stopped
    environment:
    - WEBSOCKET_ENABLED=true
    - ROCKET_PORT=8080
    volumes:
    - /RAID/bitwarden:/data

  bitwarden-backup:
    image: bruceforce/bw_backup
    restart: unless-stopped
    volumes:
      - /RAID/bitwarden:/data
      - ~/bitwarden_backup:/backup
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - DB_FILE=/data/db.sqlite3
      - BACKUP_FILE=/backup/backup.sqlite3
      - CRON_TIME=0 1 * * *
      - TIMESTAMP=false
      - UID=1000
      - GID=1000
        
  home-assistant:
    image: homeassistant/home-assistant
    restart: unless-stopped
    volumes:
      - ~/home-assistant:/config

  mdns-repeater:
    image: angelnu/mdns_repeater
    restart: unless-stopped
    network_mode: host
    environment:
    - hostNIC=enp4s0
    - dockerNIC=br-de87821a94e9

  plex:
    image: linuxserver/plex
    restart: unless-stopped
    volumes:
    - ~/plex/config:/config
    - /RAID/Output:/data/tesla_cam
    - /MOVIES:/data/movies
    - /TV_SHOWS:/data/tv_shows
    environment:
      VERSION: docker
      PUID: 1000
      PGID: 1000
      TZ: America/Chicago

  samba:
    image: dperson/samba
    restart: unless-stopped
    ports:
    - 139:139
    - 445:445
    volumes:
    - /RAID/Input:/mount
    environment:
      USERID: 1000
      GROUPID: 1000
      TZ: America/Chicago
    env_file:
    - .env
    read_only: true
    tmpfs:
    - /tmp
    stdin_open: true
    tty: true
    command: '-s "Mount;/mount;yes;no;no;$USERNAME" -u "$USERNAME;$PASSWORD"'

  tesla_dashcam:
    image: magicalyak/tesla_dashcam
    restart: unless-stopped
    environment:
    - TZ=America/Chicago
    volumes:
    - /RAID/Input:/root/Import
    - /RAID/Output:/root/Videos/Tesla_Dashcam
    command: '--swap --rear --delete_source --layout DIAMOND --quality HIGH --fps 33 --gpu_type nvidia --compression veryslow /root/Import'

  blue-iris:
    image: leonowski/docker-blueiris:run_as_service
    restart: unless-stopped
    # privileged: true
    init: true
    environment:
    - TZ=America/Chicago
    #- RESOLUTION=1270x650x24
    #- RESOLUTION=1440x768x24
    #- RESOLUTION=1640x768x24
    #- RESOLUTION=1918x902x24
    #ports:
    #- 8082:8080
    volumes:
    - /RAID/blue-iris:/home/wineuser/prefix:rw
    logging:
      options:
        max-size: 5m
        max-file: "2"
    command: -c /etc/supervisor/conf.d/supervisord-service.conf

#  frigate:
#    image: blakeblackshear/frigate:stable-amd64nvidia
#    restart: unless-stopped
#    runtime: nvidia
#    privileged: true
#    shm_size: '1g'
#    ports:
#    - 5000:5000
#    volumes:
#    - /etc/localtime:/etc/localtime:ro
#    - ~/frigate:/config
#    - /RAID/frigate/recordings:/media/frigate/recordings
#    - /RAID/frigate/clips:/media/frigate/clips
#    environment:
#      - NVIDIA_VISIBLE_DEVICES=all
#      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,video
#    env_file:
#    - frigate.env
#
#  frigate-live-view:
#    build: frigate-live-view/.
#    restart: unless-stopped
#    ports:
#    - 5001:80
#
#  double-take:
#    image: jakowenko/double-take
#    restart: unless-stopped
#    volumes:
#    - ~/double-take:/.storage
#    ports:
#    - 3000:3000
#    env_file:
#    - double-take.env

  deepstack-ai:
    image: deepquestai/deepstack:gpu
    restart: unless-stopped
    runtime: nvidia
    environment:
    - VISION-DETECTION=True
    - VISION-FACE=True
    volumes:
    - /RAID/deepstack/datastore:/datastore

  mqtt-broker:
    image: eclipse-mosquitto
    restart: unless-stopped
    ports:
    - 1883:1883
    volumes:
    - ./mosquitto/config:/mosquitto/config
    - ~/mosquitto/data:/mosquitto/data
