services:
  frigate:
    #image: ghcr.io/blakeblackshear/frigate:stable
    image: ghcr.io/blakeblackshear/frigate:0.15.0-beta4
    restart: unless-stopped
    privileged: true
    shm_size: '1g'
    ports:
    - 5000:5000
    volumes:
    - ./frigate/config.yml:/config/config.yml
    - /dev/dri/renderD128
    env_file:
    - frigate/frigate.env
