services:
  frigate:
    image: ghcr.io/blakeblackshear/frigate:stable-standard-arm64
    restart: unless-stopped
    privileged: true
    shm_size: '1g'
    ports:
    - 5000:5000
    - 8554:8554
    - 8555:8555/tcp
    - 8555:8555/udp
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - ./frigate/config.yml:/config/config.yml
    - ~/frigate:/config
#    - /Blue-Iris:/media/frigate
    env_file:
    - frigate/frigate.env
    logging:
      driver: "json-file"
      options:
          max-size: "50m"

