services:
  unifi-network-application:
    image: lscr.io/linuxserver/unifi-network-application:latest
    restart: unless-stopped
    environment:
    - PUID=1000
    - PGID=1000
    - TZ=America/Chicago
    - MONGO_USER=unifi
    - MONGO_HOST=unifi-db
    - MONGO_PORT=27017
    - MONGO_DBNAME=unifi
    - MONGO_AUTHSOURCE=admin
    - MEM_LIMIT=1024 #optional
    - MEM_STARTUP=1024 #optional
    env_file:
    - mongo.env
    ports:
    - 8443:8443
    - 3478:3478/udp
    - 10001:10001/udp
    - 8080:8080
    - 1900:1900/udp #optional
    - 8843:8843 #optional
    - 8880:8880 #optional
    - 6789:6789 #optional
    - 5514:5514/udp #optional
    - 7444:7444/tcp
    - 7550:7550/tcp
    - 7442:7442/tcp
    volumes:
    - ~/unifi-network-application:/config

  unifi-db:
    image: docker.io/mongo:7.0
    restart: unless-stopped
    environment:
    - MONGO_INITDB_ROOT_USERNAME=root
    - MONGO_USER=unifi
    - MONGO_DBNAME=unifi
    - MONGO_AUTHSOURCE=admin
    env_file:
    - mongo.env
    volumes:
    - ~/mongo/config:/config
    - ~/mongo/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh:ro
        
  home-assistant:
    image: homeassistant/home-assistant
    restart: unless-stopped
    volumes:
    - ~/home-assistant:/config
    ports:
    - 8123:8123
    - 5683:5683/udp

  esphome:
    image: esphome/esphome
    restart: unless-stopped
    volumes:
    - ~/esphome/config:/config
    - /etc/localtime:/etc/localtime:ro
    network_mode: host
    privileged: true

  mdns-repeater:
    image: angelnu/mdns_repeater
    restart: unless-stopped
    network_mode: host
    environment:
    - hostNIC=eno1
    - dockerNIC=br-e6cbe9582c38

  plex:
    image: lscr.io/linuxserver/plex:latest
    ports:
    - 32400:32400
    environment:
      PUID: 1000
      PGID: 1000
      TZ: America/Chicago
      VERSION: docker
    env_file:
    - .env
    volumes:
    - ~/plex/config:/config
    - /Media/Movies:/movies
    - /Media/Tv_Shows:/tv_shows
    restart: unless-stopped

#  samba:
#    image: dperson/samba
#    restart: unless-stopped
#    ports:
#    - 139:139
#    - 445:445
#    volumes:
#    - /RAID/Input:/mount
#    environment:
#      USERID: 1000
#      GROUPID: 1000
#      TZ: America/Chicago
#    env_file:
#    - .env
#    read_only: true
#    tmpfs:
#    - /tmp
#    stdin_open: true
#    tty: true
#    command: '-s "Mount;/mount;yes;no;no;$USERNAME" -u "$USERNAME;$PASSWORD"'

#  tesla_dashcam:
#    #build:
#    #  dockerfile: ../../tesla_dashcam/Dockerfile
#    image: magicalyak/tesla_dashcam
#    restart: unless-stopped
#    environment:
#    - TZ=America/Chicago
#    volumes:
#    - /RAID/Input:/root/Import
#    - /RAID/Output:/root/Videos/Tesla_Dashcam
#    command: '--swap --rear --delete_source --layout DIAMOND --quality HIGH --fps 33 --gpu_type nvidia --compression veryslow /root/Import'

  frigate:
    #image: ghcr.io/blakeblackshear/frigate:stable
    #image: ghcr.io/blakeblackshear/frigate:0.15.0-beta4
    image: ghcr.io/blakeblackshear/frigate:0.15.0-beta7
    restart: unless-stopped
    privileged: true
    shm_size: '1g'
    ports:
    - 5000:5000
    - 8554:8554
    - 8555:8555/tcp
    - 8555:8555/udp
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - ./frigate/config.yml:/config/config.yml
    - ~/frigate:/config
    - /Blue-Iris:/media/frigate
    - /dev/bus/usb:/dev/bus/usb
    env_file:
    - frigate/frigate.env
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    logging:
      driver: "json-file"
      options:
          max-size: "50m"

  mqtt-broker:
    image: eclipse-mosquitto
    restart: unless-stopped
    ports:
    - 1883:1883
    volumes:
    - ./mosquitto/config:/mosquitto/config
    - ~/mosquitto/data:/mosquitto/data
